# Generated by Django 3.2.5 on 2021-11-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departure_airport',
            name='id',
        ),
        migrations.AlterField(
            model_name='departure_airport',
            name='airport_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
