# Generated by Django 3.2.5 on 2021-11-25 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20211124_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('card_id', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=10)),
                ('sex', models.CharField(choices=[('M', '女性'), ('F', '男性')], default=None, max_length=1)),
                ('user_type', models.CharField(choices=[('A', ' 乘客'), ('B', '值机柜台工作人员'), ('C', '客服人员'), ('D', '调度中心工作人员')], max_length=1)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('departure_time', models.DateTimeField()),
                ('time_of_flight', models.TimeField()),
                ('air_type', models.CharField(choices=[('A', '大型客机'), ('B', '中型客机'), ('C', '小型客机')], max_length=1)),
                ('terminal', models.IntegerField(default=None)),
                ('departure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departure', to='web.departure_airport')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='web.departure_airport')),
            ],
        ),
    ]
