# Generated by Django 3.2.5 on 2021-12-18 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_flight_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight_plan',
            fields=[
                ('plan_id', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('seat_type', models.CharField(choices=[('A', '头等舱'), ('B', '商务舱'), ('C', '经济舱')], max_length=1)),
                ('safe_type', models.CharField(choices=[('A', '普通'), ('B', '中级'), ('C', '高级')], default='A', max_length=1)),
                ('charge', models.IntegerField()),
                ('max_check', models.IntegerField(default=None)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='null', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('M', '女性'), ('F', '男性')], default='M', max_length=1),
        ),
    ]
