# Generated by Django 3.2.5 on 2021-12-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20211218_1621'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tradeFlight', to='web.flight')),
                ('passenger_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='tradeUser', to='web.user')),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tradePlan', to='web.flight_plan')),
            ],
            options={
                'unique_together': {('passenger_id', 'flight_id', 'plan_id')},
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_id', models.CharField(max_length=3)),
                ('state', models.CharField(choices=[('0', '未选'), ('1', '已选')], default='0', max_length=1)),
                ('flight_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_to_flight', to='web.flight')),
                ('passenger_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='seat_to_user', to='web.user')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seaType', to='web.flight_plan')),
            ],
            options={
                'unique_together': {('seat_id', 'flight_id')},
            },
        ),
    ]
