# Generated by Django 3.2.5 on 2021-12-24 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_seat_trade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='passenger_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seat_to_user', to='web.user'),
        ),
    ]
