# Generated by Django 3.2.5 on 2021-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_seat_passenger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('A', '头等舱'), ('B', '商务舱'), ('C', '经济舱')], max_length=1),
        ),
    ]
