# Generated by Django 3.2.5 on 2021-12-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_seat_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='用户数', max_length=50, null=True)),
                ('number', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
